In [2]:
%load_ext jupyter_ai

In [3]:
%%ai chatgpt -f code

Consider the following text

...........
.....###.#.
.###.##..#.
..#.#...#..
....#.#....
.##..S####.
.##..#...#.
.......##..
.##.#.####.
.##..##.##.
...........

This text represents an n x m grid. You start where the S column indicates (row 5, column 5)

On every iteration you can move up down left or right, but you can't move into a wall (walls are indicated by #). So from S you could move 
up or left but not down or right because there are walls

I want to represent the possible directions you can travel as an adjacency matrix. So from (5, 5) you can go up (4, 5) or left (5, 4).
Parse the text into an adjacency matrix in numpy

/Users/evanthomas/github.com/ethomas2/advent-of-code-2023/venv/lib/python3.11/site-packages/langchain_community/llms/openai.py:1057: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain_community.chat_models import ChatOpenAI`
  warnings.warn(


In [22]:
import numpy as np

text = """...........
.....###.#.
.###.##..#.
..#.#...#..
....#.#....
.##..S####.
.##..#...#.
.......##..
.##.#.####.
.##..##.##.
..........."""

grid = []

for line in text.split("\n"):
    if line:
        grid.append(list(line))

n = len(grid)
m = len(grid[0])

adj_matrix = np.zeros((n*m, n*m))

for i in range(n):
    for j in range(m):
        if grid[i][j] != "#":
            if i > 0 and grid[i-1][j] != "#":
                adj_matrix[i*m+j, (i-1)*m+j] = 1
            if i < n-1 and grid[i+1][j] != "#":
                adj_matrix[i*m+j, (i+1)*m+j] = 1
            if j > 0 and grid[i][j-1] != "#":
                adj_matrix[i*m+j, i*m+j-1] = 1
            if j < m-1 and grid[i][j+1] != "#":
                adj_matrix[i*m+j, i*m+j+1] = 1

adj_matrix

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [23]:
print(adj_matrix.shape)
print(grid)


(121, 121)
[['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '#', '#', '#', '.', '#', '.'], ['.', '#', '#', '#', '.', '#', '#', '.', '.', '#', '.'], ['.', '.', '#', '.', '#', '.', '.', '.', '#', '.', '.'], ['.', '.', '.', '.', '#', '.', '#', '.', '.', '.', '.'], ['.', '#', '#', '.', '.', 'S', '#', '#', '#', '#', '.'], ['.', '#', '#', '.', '.', '#', '.', '.', '.', '#', '.'], ['.', '.', '.', '.', '.', '.', '.', '#', '#', '.', '.'], ['.', '#', '#', '.', '#', '.', '#', '#', '#', '#', '.'], ['.', '#', '#', '.', '.', '#', '#', '.', '#', '#', '.'], ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.']]


In [7]:
%%ai chatgpt -f code


I want to know all the possible locations I can get to in exactly 64 steps. To do this
1. Create a vector that has the start position (5, 5). You should get this by inspecting grid
2. Raise adj_matrix to the 64th power and multiply it by the vector

output the final vector and the number of possible locations in the final vector (ie the number of entires in the vector with value > 1)

/Users/evanthomas/github.com/ethomas2/advent-of-code-2023/venv/lib/python3.11/site-packages/langchain_community/llms/openai.py:1057: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain_community.chat_models import ChatOpenAI`
  warnings.warn(


In [36]:
start_position = (5, 5)
start_index = start_position[0] * m + start_position[1]
initial_vector = np.zeros(n * m)
initial_vector[start_index] = 1

steps = 6
final_vector = np.linalg.matrix_power(adj_matrix, steps) @ initial_vector
num_possible_locations = np.sum(final_vector > 0.5)

final_vector, num_possible_locations

(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  9.,  0., 16.,
         0.,  7.,  0.,  0.,  0.,  1.,  0., 10.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0., 47.,  0., 32.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0., 49.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         3.,  0., 34.,  0., 13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.]),
 16)

In [42]:
%%ai chatgpt -f code

The above code seems to work. Using the above code as a template write some code that opens the file at "src/d21/input". 
That file will contain a grid in the same format as the text above. Parse the grid and figure out how many locations are possible
after 64 steps. Organize the code reasonably into nice functions and comment the code as appropriate

/Users/evanthomas/github.com/ethomas2/advent-of-code-2023/venv/lib/python3.11/site-packages/langchain_community/llms/openai.py:1057: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain_community.chat_models import ChatOpenAI`
  warnings.warn(


In [64]:
import numpy as np

def parse_grid_to_adj_matrix(grid):
    n = len(grid)
    m = len(grid[0])
    adj_matrix = np.zeros((n*m, n*m))
    
    for i in range(n):
        for j in range(m):
            if grid[i][j] != "#":
                if i > 0 and grid[i-1][j] != "#":
                    adj_matrix[i*m+j, (i-1)*m+j] = 1
                if i < n-1 and grid[i+1][j] != "#":
                    adj_matrix[i*m+j, (i+1)*m+j] = 1
                if j > 0 and grid[i][j-1] != "#":
                    adj_matrix[i*m+j, i*m+j-1] = 1
                if j < m-1 and grid[i][j+1] != "#":
                    adj_matrix[i*m+j, i*m+j+1] = 1
    
    return adj_matrix

def count_possible_locations(adj_matrix, steps, initial_vector):
    print(adj_matrix)
    print(adj_matrix.shape)
    #start_position = np.argwhere(adj_matrix == ord("S"))[0]
    #start_index = start_position[0] * m + start_position[1]
    #initial_vector = np.zeros(n * m)
    #initial_vector[start_index] = 1

    final_vector = np.linalg.matrix_power(adj_matrix, steps) @ initial_vector
    num_possible_locations = np.sum(final_vector >= 1)
    
    return final_vector, num_possible_locations

def parse_vector_to_grid(vector):
    grid = []
    for i in range(n):
        row = []
        for j in range(m):
            index = i * m + j
            if grid[i][j] == "#":
                row.append("#")
            elif vector[index] <= 0.005:
                row.append(".")
            else:
                row.append("O")
        grid.append(row)
    return grid

def parse_file(filename):
    with open(filename, "r") as file:
        grid = [list(line.strip()) for line in file.readlines() if line.strip()]
        m,n = len(grid), len(grid[0])
        print("grid shape", m, n, m * n)
               
    return grid

# config
filename = "/Users/evanthomas/github.com/ethomas2/advent-of-code-2023/src/d21/input"
steps = 6

# parse file
grid = parse_file(filename)
nrows, ncols = len(grid), len(grid[0])
start_idx = next(nrows * r + c for r in range(nrows) for c in range(ncols) if grid[r][c] == 'S') 
start_position = np.zeros(((nrows * ncols), 1))
start_position[start_idx] = 1

# compute
adj_matrix = parse_grid_to_adj_matrix(grid)
final_vector, num_possible_locations = count_possible_locations(adj_matrix, steps, start_position)
print('Answer', num_possible_locations)
# parse_vector_to_grid(final_vector), num_possible_locations

grid shape 131 131 17161
[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]
(17161, 17161)
Answer 42
